# Generated by Django 5.2.9 on 2025-12-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='naver_id',
            field=models.CharField(blank=True, help_text='네이버 고유 ID', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('kakao', 'Kakao'), ('google', 'Google'), ('naver', 'Naver')], default='normal', help_text='로그인 타입', max_length=20),
        ),
    ]
