# Generated by Django 5.2.9 on 2025-12-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Festival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="축제명")),
                ("region", models.CharField(max_length=50, verbose_name="지역")),
                ("location", models.CharField(max_length=300, verbose_name="장소")),
                ("period", models.CharField(max_length=100, verbose_name="개최 기간")),
                (
                    "month",
                    models.IntegerField(help_text="1-12", verbose_name="시작 월"),
                ),
                ("description", models.TextField(verbose_name="간단 설명")),
                (
                    "detailed_description",
                    models.TextField(blank=True, verbose_name="상세 설명"),
                ),
                ("image", models.URLField(max_length=500, verbose_name="이미지 URL")),
                (
                    "fee",
                    models.CharField(
                        default="무료", max_length=100, verbose_name="입장료"
                    ),
                ),
                (
                    "contact",
                    models.CharField(blank=True, max_length=100, verbose_name="연락처"),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="웹사이트"
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="태그")),
                (
                    "programs",
                    models.JSONField(blank=True, default=list, verbose_name="프로그램"),
                ),
                (
                    "transportation",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="교통 정보"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
            ],
            options={
                "verbose_name": "축제",
                "verbose_name_plural": "축제 목록",
                "db_table": "festivals",
                "ordering": ["month", "name"],
            },
        ),
    ]
